#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: barramento-de-eventos-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
      #rótulo, app não tem nada de especial, pode ser qualquer coisa
      #Deployment vai selecionar todo Pod qe tiver esse rótulo
      app: barramento-de-eventos
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim, serão selecionados por esse deployment
        app: barramento-de-eventos
    spec:
      containers:
        - name: barramento-de-eventos
          image: matheusgalbiati/barramento-de-eventos
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  # Ip interno, NÃO acessível fora do cluster
  type: ClusterIP
  selector:
    # todo Pod que tiver essa tag fará parte desse serviço
    app: barramento-de-eventos
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      # o nó recebe requisições nessa porta
      port: 10000
      # e direciona para essa porta do Pod
      targetPort: 10000