#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: lembretes-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
      #rótulo, app não tem nada de especial, pode ser qualquer coisa
      #Deployment vai selecionar todo Pod qe tiver esse rótulo
      app: lembretes
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim, serão selecionados por esse deployment
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: matheusgalbiati/lembretes:0.0.1
          resources:
            limits:
              memory: 256Mi
              cpu: 1